trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore LubeAnalyst.csproj
  displayName: 'Restore API'

- script: dotnet build LubeAnalyst.csproj --configuration $(buildConfiguration)
  displayName: 'Build API'

- script: dotnet publish LubeAnalyst/LubeAnalyst.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/api
  displayName: 'Publish API'

- script: dotnet publish ProcessLabTestFunction/ProcessLabTestFunction.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/func
  displayName: 'Publish Function'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-connection'
    appName: 'lube-analyst-api'
    package: '$(Build.ArtifactStagingDirectory)/api'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'azure-connection'
    appName: 'processlabtest-func'
    package: '$(Build.ArtifactStagingDirectory)/func'