trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

# Install .NET
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Restore
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'LubeAnalyst.csproj'

# Build
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'LubeAnalyst.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Publish
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'LubeAnalyst.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api'

# 🔥 Archive (VERY IMPORTANT)
- task: ArchiveFiles@2
  displayName: 'Archive API'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/api'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/api.zip'
    replaceExistingArchive: true

# 🔥 Deploy ZIP
- task: AzureWebApp@1
  displayName: 'Deploy API'
  inputs:
    azureSubscription: 'azure-connection'
    appName: 'lube-analyst-api'
    package: '$(Build.ArtifactStagingDirectory)/api.zip'